### ISSUE TITLE
Put logos of BIP 101 supporters on website

### ISSUE THREAD

**Issue by mikehearn** [bitcoinxt/website#16]
This letter pledges support for BIP 101 from major Bitcoin companies:

http://blog.blockchain.com/wp-content/uploads/2015/08/Industry-Block-Size-letter-All-Signed1.pdf

They are:
- BitPay
- Bitnet
- Circle
- Blockchain
- Xapo
- itBit
- BitGo
- KncMiner

As right now XT is the only implementation of BIP 101 I think we should put these companies logos on the website under a new "We support BIP 101" section, or so.

**Comment by josephcastan** [comment]
Working on it. "Who's Onboard" title looks best in the top menu. "We support BIP101" is too long and corny.

**Comment by josephcastan** [comment]
Done. See the pull request.

**Comment by luke-jr** [comment]
Didn't at least KncMiner change their mind already since this letter?

**Comment by mikehearn** [comment]
Resolved by @NxtChg 

@luke-jr I think their current position is they'll roll with BIP 100 or BIP 101. At any rate, they signed the letter.
