### ISSUE TITLE
Add Coinbase to the supporters list

### ISSUE THREAD

**Issue by Har01d** [bitcoinxt/website#32]
I believe we should add Coinbase to the "WHO'S ONBOARD" page: https://bitcoinmagazine.com/articles/coinbase-ceo-brian-armstrong-bip-is-the-best-proposal-we-ve-seen-so-far-1446584055

**Comment by mikehearn** [comment]
Sure, if someone wants to write a patch to do that, I'm all for it.

**Comment by Har01d** [comment]
@mikehearn, see https://github.com/bitcoinxt/website/pull/33
