### ISSUE TITLE
Remove country flags

### ISSUE THREAD

**Issue by dagurval** [bitcoinxt/website#48]
Languages know no borders, so the country flags where selecting language should be removed.

Suggest replacing it with the name of the language, in the language itself, like bitcoincash.org does. We need a solution that supports many languages.

@chaintip 1 year

**Comment by chaintip** [comment]
`0.00879166 BCH`| `~  12.87 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4wke9usgcm3g4xzwl8m0mtv555rvz57deqdd) to this issue by @dagurval.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/6), get a pull request merged with ```@chaintip fixes #48``` in the creation comment.

**Comment by chaintip** [comment]
@dagurval... I'm a bit stupid at the moment. I only understand days. If you want 1 year, please use 365 days otherwise I only pick up the '@chaintip' and it defaults to 30 days.

**Comment by dagurval** [comment]
There are multiple solutions for this issue. Closing.

**Comment by chaintip** [comment]
`0.00879166 BCH`| `~  13.28 USD` has now been claimed by @dagurval when pull request [#54](http://github.chaintip.org/bitcoinxt/website/pull/54) was merged.
