### ISSUE TITLE
Support internationalization

### ISSUE THREAD

**Issue by dagurval** [bitcoinxt/website#49]
We want the website to be in multiple languages, but easily maintainable. Right now, translation is done by copy/pasting the whole website and then translating the copy.

This is impossible to maintain. We need proper internationalization support. So either:

- Find a jekyll plugin that adds internationalization, and fully implement it.
- Or if jekyll doesn't provide a solution, replace jekyll with something that does.

@chaintip 365 days

**Comment by chaintip** [comment]
`0.02197916 BCH`| `~  32.14 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40hdppx4rscrxfqscdwy87k2c3ec5zpjuyat) to this issue by @dagurval.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/7), get a pull request merged with ```@chaintip fixes #49``` in the creation comment.

**Comment by kbsezginel** [comment]
Jekyll definitely provides a solution. I am not exactly sure how but [bitcoincash.org repo](https://github.com/zquestz/bitcoincash) might be helpful as a reference.

**Comment by EchterAgo** [comment]
I am working on this using the jekyll-multiple-languages-plugin https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

**Comment by chaintip** [comment]
`0.02197916 BCH`| `~  33.16 USD` has now been claimed by @EchterAgo when pull request [#51](http://github.chaintip.org/bitcoinxt/website/pull/51) was merged.
