### ISSUE TITLE
Update the russian translation

### ISSUE THREAD

**Issue by dagurval** [bitcoinxt/website#55]
The russian translation is outdated. Since we didn't have a good support for internationalization (fixed in #51), we don't know what's up-to-date and what isn't.

Compare [ru.yml](../tree/master/_i18n/ru.yml) with [en.yml](../tree/master/_i18n/en.yml) and update translation.

@chaintip 365 days

**Comment by chaintip** [comment]
`0.01010399 BCH`| `~  15.28 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4y4fr3e526gr32d8prfkxz3fsvwsvpd3kypw) to this issue by @dagurval.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/11), get a pull request merged with ```@chaintip fixes #55``` in the creation comment.

**Comment by chaintip** [comment]
`0.01010399 BCH`| `~  12.26 USD` has now been claimed by @bchtrue when pull request [#56](http://github.chaintip.org/bitcoinxt/website/pull/56) was merged. This will be sent to your wallet once you link it with chaintip.
